### ISSUE TITLE
Leaves a Badge/Token/Ticket

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#25]
When I change to this

> # Set minimum resources (Amount for the bot to leave for manual play)
> minShards 0
> minTokens 0
> minEnergyPercentage 1
> minTickets 0
> minBadges 0

The bot always leaves one point, even though I have setup Ticket usage to 1 for example.

My max points look like this 

> # Set maximum resources (For calculating value when you have guild perks)
> maxShards 7
> maxTokens 12
> maxTickets 12
> maxBadges 13

PS: I just wanted to say thanks for picking up this great bot again!

**Comment by Fortigate** [comment]
No worries, I've enjoyed making it :)

The bot currently works by counting red pixels in the bar to get the percentage, and dividing that by max tickets. but due to the 2 pixels of shading at the start of the bar being a different colour low ticket counts are inaccurate. I'll see if adding on the shaded pixels before calculating breaks the count in any other scenarios and put it in with the next release.

**Comment by Fortigate** [comment]
Fixed in https://github.com/Betalord/BHBot/commit/74fb507fbb5e69e5d478b4292de76d18c867fb0a
