### ISSUE TITLE
Another Suggestion

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#26]
I would have two more Suggestions.

First is to have an autoidle mode, where the bot logs off for a certain amount of time, so other players wont get suspicious, because I am online most of the time.

Second would be to save Shrine/Boss until the end of a Raid+T/G. 
Since the raids got so much harder in comparison to R4/R5,even a good team can be torn apart on Heroic.
Saving Shrines for the boss can help alot with that problem.
(And I don´t want to know what they do with R7 in a few weeks)

I would find it awesome if these two things could also be implemenented at some point.
But even without those features, this is still an awesome Bot, and I just wanted to say thanks again! 

PS: Thanks for the revive function! It helps alot on Trials 🥇

**Comment by Fortigate** [comment]
First request exists already in a roundabout fashion, I use Z-Cron on windows to run my account for 30mins every 6 hours, which comfortably clears free to play regen with `hideWindowOnRestart 1` in settings to hide the chrome window on launch, and a batch file with; 

`taskkill /f /im "chrome.exe"`
`taskkill /f /im "java.exe"`

to kill the proccess and browser after 30mins. It's not the cleanest solution but probably more reliable and less resource intensive than something I could hack together with the current bot code.

Second request I was looking at last night, I think I know a clean way to implement it. I want to prioritise ads claiming first though, as it's something that should have been fixed in a version months ago, and a major source of F2P gems.

Glad your finding it useful!

**Comment by Larrush** [comment]
I will try it out! That works more than fine for me.

And there is no need to hurry with the save Shrines for the Boss feature. I just thought I´d bring it up.

Looking forward to the ad feature :)

**Comment by Larrush** [comment]
I just thought one more nice feature would be to have a max limit to familiars (green, blue, red, yellow).
Since I have already 50 of some that I don´t need so much and others that I would need in the same dungeon.

So I can´t just decline certain familiars. Again no hurry on that if implementable!

**Comment by Larrush** [comment]
> `taskkill /f /im "chrome.exe"`
> `taskkill /f /im "java.exe"`

If I do it like that, I sometimes get a Chrome Automation Extension crash, which prevents Chrome to properly shut down.
Do you maybe know a solution to that? 

My batch file looks like that
`@ECHO OFF
taskkill /f /im "chrome.exe"
taskkill /f /im "java.exe"
EXIT`

I might be doing something wrong, since I am not familiar with Z-cron or batch files

**Comment by Fortigate** [comment]
I used to get issues like that as I wasn't able to run the script as admin with a scheduler, which was one of the main reasons I use z-cron. In z-cron go to Job Settings - Run As Settings and configure with an admin account, that should fix it.

**Comment by Larrush** [comment]
I finally made it work :D 

Apparently only setting up the option in Z-Cron isn´t enough, I also had to start Z-Cron as Admin so it can actually use the admin feature too.
I tried everything but the most obvious thing at last.

Big thanks for the advice, otherwise I would have needed a few more days!

**Comment by bbicudo** [comment]
Auto fishing would also be great!

**Comment by Larrush** [comment]
Naah no need to waste time on that.
There is already a great fishing bot out there.
Just search in google "fisherbot" bitheroes.
It does what its supposed to do and not more ;)
I mean he might be able to make it even better but for now its good.

**Comment by bbicudo** [comment]
The fisherbot doesn't allow you to keep on working on your PC, that's why i came up with the fishing XD 

BHBOT is very good because you can focus on other things while it does all the work hehe

**Comment by Fortigate** [comment]
Yup there's a great bot already available, unfortunately running it at the same time as the bot can cause some issues due to the screen moving to align the game, but otherwise I've had no issues running it.

As for introducing it to the bot I looked into it but it's not really feasible, the bot works on 2-5 second reaction times to take screenshots and process them, to catch the counter on 100% on fishing requires at the very least sub second timing, which would require a lot of processing power if it worked at all.

**Comment by Fortigate** [comment]
Auto shrine saving (for trials + raids) added in https://github.com/Betalord/BHBot/commit/3bb7d57b0c65a918826d07de01c504f091786bc2. I've got another feature I want to add in tomorrow then will release v32.

Familiar declining would require creating and loading image files for each rare familiars name, so its pretty far back on the list of things to work on, will keep it in mind though.
