### ISSUE TITLE
New ads in kong site.

### ISSUE THREAD

**Issue by zenblob** [Betalord/BHBot#82]
A new type of ads (animated banners) make considerable confusion for the client, who cannot identify the game window.

I solved with adblock. maybe can be useful for someone.

**Comment by Fortigate** [comment]
Thanks for the heads up, unless there's a static close or skip button there's not much we can do about the ads that appear in the games frame apart from using an adblocker to stop them from running.

**Comment by ilpersi** [comment]
I haven't seen this happening on my bots yet. One question: in the settings.ini do you happen to have the old `doAds` setting in place?

**Comment by Fortigate** [comment]
I saw it when I was playing an account on a new browser, the ad is loaded instead of the game in the frame, and does not skip until a button is pressed. So the bot is unable to run as all it detects is the ad in the screenshots.

As the ads are dynamic and changing there's not much we can do to close them and need to have an adblocker active in order to run the bot.
